openwrt: Fix build with GCC-10 as host compiler
The source packages uboot-kirkwood + uboot-sunxi use the host compiler to
build the dtc binary. With gcc-10, the option -fno-common is now the
default behavior. Thus multiple definitions of the same variable are now
forbidden and results in following error during linking:

  HOSTLD  scripts/dtc/dtc
  /usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
  collect2: error: ld returned 1 exit status

The easiest workaround is to add the upstream commit 018921ee79d3 ("Remove
redundant YYLOC global declaration").

Signed-off-by: Sven Eckelmann <sven@narfation.org>